_target_: src.models.nets.light_final.LightT2M
motion_dim: ${data.motion_dim}
max_motion_len: 200
text_dim: 512
pos_emb: "cos"
stage_dim: "256*4"
num_groups: 16
patch_size: 8

# for mamba
rms_norm: false
fused_add_norm: true
ssm_cfg:
  d_state: 16
  d_conv: 4
  expand: 2