_target_: diffusers.DDPMScheduler
num_train_timesteps: 1000
beta_start: 0.0001
beta_end: 0.02
# beta_start and beta_end will be not activated when using squaredcos_cap_v2
beta_schedule: "linear"
variance_type: "fixed_small"
# need to conduct ablation studies
clip_sample: false
prediction_type: 'epsilon'